apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: sk000-
namespace: skala-practice

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      env: dev
      app: sk000-my-app

commonAnnotations:
  contact: "himang10@sk.com"

patches:        # base 이름 기준
  - path: patch-deploy.yaml
    target:
      kind: Deployment
      name: my-app     # base 이름 기준
  - path: replace-images.yaml
    target:
      kind: Deployment
      name: my-app     # base 이름 기준
  - path: patch-service.yaml
    target:
      kind: Service
      name: my-app     # base 이름 기준
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: my-app     # base 이름 기준
  - path: remove-annotation.yaml
    target:
      kind: Deployment
      name: my-app     # base 이름 기준
  # ConfigMap과 Secret 패치 추가
  - path: patch-configmap.yaml
    target:
      kind: ConfigMap
      name: my-app-config
  - path: patch-secret.yaml
    target:
      kind: Secret
      name: my-app-secrets
images:
  - name: amdp-registry.skala-ai.com/skala25a/sk000-my-app
    newTag: 1.0.0   # 새로운 버전으로 변경
