apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - name: svc1
      port: 9090     # 예: mgmt 포트 바꾸고 싶을 경우
      targetPort: 9090
    - name: svc2
      port: 8888     
      targetPort: 8888

